language: java
deploy:
  skip_cleanup: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: email@bryton.io
  password:
    secure: a8+7GBawSwsqky3VxSJDZrzSORHczY2IdDDzQKaCbRGwFoonMplWwFDXswuSWW5zDIHa7JqLHOtXnmp0Lh3l7zDBruqcW8hC7iOOPE53C5wIPGWrEXFAOV7lrPdGBfD3rAaPLiRsoEi1JfuaM+4EIMalgOLPDq7uF10Wj0FSkjGYtLISk1//qykm8SMp585DVfrRN6fV0aIjibW1LdOzz/P/auBYaYwULSoINmwhHJZVBP5hNfgShLxYaL5Le13zXNXacYeEv8gB13dUot2mAPaYWsSuEnNnPrShS7LmE/Hfa1CQfXZMqZAkRHa4yDAlRRjI7ofOveK6BUhIilY2eoJj0nMCUBDCbYcR9QkvtSSYPhNVxR+yGx7GGn8t+7i1vjAsD4zAPxlL1Fqsc358MUVkNcjBqrudbE0uOLQ8XtYe3T4I3+IWo6GNkmjO8iqmy2KqX5msfPAqyvCON4NmnKu6DBF948qa2WYEYkXlApcHy37YUdrh45atFZfL3SdiIYTN8u4bi76dBxjRu2u+jHBFqz00pLQrnGUDuQdz1Vp4t0dz9kDaNH4knTy7DTOaPiF3WK/b30lDdtkGNGWsmOwz3LHHbJdsbwLVqMF7zc0ji3TkMVlGuq7dBijzSQkuWHIzrSjWNUTPNXTcO+zDp44NRboNSMeqccUgbphoX3M=
  organization: august-duet.org
  space: development
  on:
    repo: revaturelabs/hydra-address-service
    branch: develop
